app/.env.template
app/README.md
app/package.json
app/src/App.vue
app/src/components/BaseInput.vue
app/src/components/LayoutHeader.vue
app/src/index.css
app/src/router/index.ts
app/src/shims.d.ts
app/src/store/data.ts
app/src/store/wallet.ts
app/src/utils/constants.ts
app/src/utils/ethers.ts
app/src/utils/formatters.ts
app/src/utils/utils.ts
app/src/views/GrantRegistryGrantDetail.vue
app/src/views/GrantRegistryList.vue
app/src/views/GrantRegistryNewGrant.vue
app/src/views/Home.vue
app/tailwind.config.js
contracts/package.json
contracts/scripts/app.ts
package.json
yarn.lock

Closes #11, closes #18
- Implements everything described in #11
- Setup script forks mainnet, deploys `GrantRegistry` and creates dummy grants with arbitrary data
- Read `app/README.md` for setup/troubleshooting instructions when testing against a forked Hardhat node
- Didn't focus on designs too much, just pulled and modified some Tailwind UI components (for example, edit page is basically a copy/paste of the New Grant page to save time for now)
- Wallet connection can be a bit flaky, so created #14 to track this

Grant registry UI prototyping

---

contracts/contracts/GrantRegistry.sol
contracts/contracts/GrantRound.sol
contracts/hardhat.config.ts
contracts/package.json
contracts/test/GrantRegistry.test.ts
contracts/test/GrantRound.test.ts
contracts/test/utils.ts
yarn.lock

GrantsRound contract with tests

---

contracts/.solhint.json
contracts/contracts/GrantRound.sol
contracts/contracts/GrantRoundManager.sol
contracts/hardhat.config.ts
contracts/package.json
contracts/scripts/app.ts
contracts/test/GrantRound.test.ts
contracts/test/GrantRoundManager.test.ts
contracts/test/utils.ts
types/src/grants.d.ts
yarn.lock

Closes #40 
Current limitations:
- Donations must have a direct pair. For example, there is an ETH/GTC pair on Uniswap V3, so this contract will let me donate ETH and will swap it to GTC. However, there is no DAI/GTC pair so donating DAI is currently not possible if GTC is the donation token
- ETH as the donation token is not supported (but you can use WETH)

Add grant round manager

---

contracts/hardhat.config.ts
contracts/package.json
yarn.lock

We need to upgrade hardhat to the latest version to account for changes in EIP-1559
This is the error I was seeing when starting the dev server:

Upgrades hardhat version (2.2.0 -> 2.5.0)

---

CONTRIBUTING.md

Trimmed down the categories on github discussions and captured that in the contributing doc here.

Adding info about github discussions

---

dcurve/src/internal/utils.ts

To discover each prediction point we filter the distribution to find the match for the grant - there are situations where the filter will not find a result and instead we should default to a match of 0.
--
Fixes: #168

fix: Fixes missing match value for when the filter fails

---

app/vite.config.ts
tsconfig.settings.json

`resolveJsonModule: true` was needed to resolve:
``` 
@dgrants/types: ../node_modules/@uniswap/token-lists/dist/index.d.ts(1,20): error TS2732: Cannot find module './tokenlist.schema.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.
```
After that was added, `esModuleInterop: true` (sorry @wildmolasses I think you advise not using this 😬 ) was needed to resolve:
```
@dgrants/types: ../node_modules/@uniswap/token-lists/dist/index.d.ts(1,8): error TS1259: Module '"/Users/mds/Documents/projects/gitcoin/dgrants/node_modules/@uniswap/token-lists/dist/tokenlist.schema"' can only be default-imported using the 'esModuleInterop' flag
@dgrants/types: ../node_modules/@uniswap/token-lists/dist/index.d.ts(1,8): error TS1259: Module …
```

build: fix errors when running 'yarn build'

---

app/src/assets/placeholder_grant.svg
app/src/components/BaseInput.vue
app/src/components/BaseSelect.vue
app/src/views/Cart.vue

i worked on the cart to get my ui in, and everything worked fine. this is a mandatory pull request and should get merged asap to continue working on it ( usdt / matching and so on ) ...
**anyway there is 2 issue here we need to be aware of and fix :**
the cart uses  `<BaseInput>` and `<BaseSelect>` Components (pre-design-created)  what i had to tweak. the `<BaseSelect>` uses some non-native fake-select-input-fields, what are hard to combine with regular native `<input>` ( see different heights on some resolutions )
Input Fields are always hard to Controll - especialy when you work with paddings, and percentage based sizes - so its not a good idea to mix different approaches to style it. I would 100% prefer if we can go a step back and remove that headless ui components and use regular …

improved ui for cart

---

app/src/router/index.ts
app/src/views/GrantRound.vue
app/src/views/GrantRoundsList.vue
contracts/scripts/app.ts
types/src/grantRounds.d.ts

- introduced new view GrantRound  which shows details of a given round
- tweak IPFS GrantRound metaPtr to include new data elements
- display new elements on GrantRound Page
- update routes so that 
- `dgrants/rounds/:address`  shows Grant round Info 
- `dgrants/rounds/:address/grants` shows the actual Grants in the GrantRound
- Tweaking the UI based on design (this could be in a standalone PR)
Here is the metaPtr structure: http://storageapi.fleek.co/thelostone-mc-team-bucket/round.json

feat: add GrantRoundPage + add metadata

---

app/src/components/GrantDetailsRow.vue
app/src/views/GrantRegistryGrantDetail.vue

- rewrote that grantdetailrow from scratch for slicker code and especially for bens concerns regarding to big grant-image  
- removed v-slot from GrantDetailsRow for share/edit buttons as i outsourced these to a dedicated navbar in the GrantRegistryGrantDetail.vue for better scalability of more interactions and a simpler codebase.
https://user-images.githubusercontent.com/569641/132556626-74e6717a-86bd-4c05-83a0-5367fb25b65b.mov

improved grants detail view

---

app/package.json
package.json
yarn.lock

This PR forces the use of an alternative version of `brorand` which does not have a circular dependency (https://github.com/buu700/brorand) on `crypto`
--
Fixes: #178
--
Tested locally and everything now loads after a `yarn build`

fix: Fixes circular dependency issue on brorand

---

CHANGELOG.md
README.md
app/CHANGELOG.md
app/package.json
contracts/CHANGELOG.md
contracts/package.json
dcurve/CHANGELOG.md
dcurve/package.json
lerna.json
package-lock.json
package.json
types/CHANGELOG.md
types/package.json
utils/CHANGELOG.md
utils/package.json
yarn.lock

This PR adds commands to the package.json to handle bumping versions. There are three commands (bump-patch, bump-minor, bump-major) which increase the version specified respectively and the short commit hash.
Currently all of our packages are in the same repo so they will get the same version bumps regardless of being changed or not. I have added the `--force-publish` flag which forces the version update to happen even if no changes are detected. Once we use lerna to break them out into separate repositories, we can utilize the independent versioning feature.
This setup does not currently manage versions in the top level package.json so that is something to discuss.
The second set of three commands (release-patch, release-minor, and release-major) move from a pre-release version which …

Add version bump commands to package.json

---

app/src/router/index.ts

I don't think we have an associated issue, but this changes the router from history to hash mode, where has mode is "Useful for web applications with no host (e.g. file://) or when configuring a server to handle any URL isn't an option"
Relevant docs here: https://next.router.vuejs.org/api/#parameters

fix: change from history to hash routing for IPFS support

---

app/src/store/cart.ts
app/src/utils/utils.ts
app/src/views/Cart.vue

Resolves two-thirds of #176
The "17,278.11 DAI" portion of the screenshot below is what this PR adds. Prior to this PR, that just said "TODO"
For now we hardcode DAI but in the future we'll need to show this based on the GrantRoundManager's `donationToken`. I thought about creating an issue for this, but I a meta "Post-POC improvements" issue would be cleaner, to avoid having tons of small issues for each TODO + simplify triaging/prioritizing after the POC. @apbendi thoughts on this?

feat: show DAI-equivalent donation amount on cart page

---

app/src/components/BaseHeader.vue
app/src/components/GrantRoundDetailsRow.vue
app/src/components/InputRow.vue
app/src/index.css
app/src/views/GrantRegistryGrantDetail.vue
app/src/views/GrantRound.vue

https://user-images.githubusercontent.com/569641/133124060-54f23335-5602-46bd-b78b-307120990a73.mov
- get rid of the left empty area for X icon
- get rid of "toggleable button" as we do not use it + was not working propper anyway
- get rid of complex css with better understandable code
- have a good solution for X icon when the row is "deletable"
Closes The Issue that i can not find from todays standup where ben showed mobile input fields ...
this does not affect any changes in any forms, just merge and done.

improved UI for InputRow component

---

app/src/components/BaseFilterNav.vue
app/src/components/GrantCard.vue
app/src/components/GrantList.vue
app/src/index.css
app/src/views/GrantRegistryList.vue

Fix #208 
It seems we are having some issues implementing what Richard have in mind / his branch because most people default to Figma to look up the design. Note that copying Richard's components as they are in his branch won't always work (because of changes to general styles, new components created, etc).
@scco Could you add [this image](https://user-images.githubusercontent.com/2486142/133216886-d75cf4af-1477-4337-be26-e20a0c2cf0ed.png) to Figma? 
I think a combination of taking a look at that image + checking your components in richard-ui3 could help.
> the grid that holds the <GrandCard> should be 4 images next to each other . check my ui3 branchs codebase to see this code here.
Done. Note that if grants < 4 it aligns to the left.
> there is no plan / reason to limit that content in …

GrantRegistryList design issues

---

app/src/components/BaseInput.vue
app/src/components/BaseSelect.vue
app/src/index.css
app/src/views/Cart.vue
app/src/views/GrantRegistryGrantDetail.vue
app/src/views/GrantRound.vue

- temporary fix for height issues when combining native inputs with non-native selects
( top = after .  bottom = before )
Closes #239
- add working rudimentary tweet buttons  that share
"Checkout {round or grant} at Gitcoins Decentral Grants App!"
+ a generated encoded Link to https://grants.gtcdao.net + route to a specific grant / round
Closes #200
https://user-images.githubusercontent.com/569641/133439774-5e369c3c-b8ef-45e3-ac36-fc4c27a7319d.mov
- styling as good as i can this bn-notify addon,
whats not very stylable ( eg i can not set a better width for a notification )
came up with the idea this notifications show "behind the scenes" as a mini terminal,
as this shows so cryptic stuff all the time right now ^^ + i think our audience 
is technical versatile and love terminals too.
ps : …

richard-random-fixes-2

---

app/src/components/BaseInput.vue
app/src/components/BaseTextarea.vue
app/src/components/InputRow.vue

There is currently a little bug, that error messages appear right
I fixed this , so error messages appear under the input.
- input v-slots can handle multiple inputs in same line ( e.g. for text-input + select-input combinations )
- a row can be deletable ( not needed now, this was planed to use for some features that we maybe have later
( e.g. add team members to your grant )

InputRow / Base Inputs ui fix

---

app/src/utils/data/grantRounds.ts
app/src/utils/data/grants.ts

Updates data helpers to use events to get new state

---

app/src/components/GrantList.vue

last commit in grant-metadata-logo didn't make it into main, so this is a fix for logo in grant list

fix grant list when no logo

---

app/src/components/BaseFilterNav.vue

old design for basefilternav was semi-optimal for small screens + a bit hard to read code,
so i worked a bit on this one to have a pragmatic lightweight good behaviour on all screensizes.
https://user-images.githubusercontent.com/569641/134041116-17d3a76f-3b16-4a1c-a6fc-39aedc09bb9f.mov
- enhanced design for small resolutions
- better scalable on more items ( e.g. when its more than 5 items )
- bit better code with less div in div in div by using some semantic tags
- outsource some css to <style> for better readability
- some more comments for better readability
( doing this cleanups also to be able to see where we have css-patterns that appear over and over to add some later on into the index.css  as i did with base-grid ...  )

improved UI BaseFilterNav

---

app/src/components/GrantDetailsRow.vue

when a grant is in active multiple rounds, it's a bit confusing for a user to see, what round made a certain matching amount, and how much a potential donation would est.  add in matching based on a specific round - as there is no context between predicted amounts, matchings and round names.
- show each round a grant is in  with all the context ( matching, round-name, 10prediction, 100prediction)
- combine  Matching + Round in a single Line
- differentiate how predictions look ( black = current matching,  grey italic = vague prediction )

fix grant detail UI, when its multiple rounds same time

---

app/src/store/cart.ts
app/src/utils/utils.ts
app/src/views/Cart.vue
dcurve/src/internal/utils.ts

- adds validation to show red alert
- disables checkout button until all fields are valid 
- makes grant name clickable
closes #268
closes #221
closes #290

chore: add checkout out validation on client + make grant name clickable

---

app/src/index.css

closes #288
the style-ability for the Onboard Lib is sadly not good enough - same for their outdated documentation of css classes to throw styles on - what in most cases not works as expected.
- there are hardcoded styles i can not modify
- some svelte compiled extra classes i can not target at all as they change names on each build
- theres no way to adjust general behaviours / templates / components to play with grids, other dom structures that would me allow to add custom icons . 
i disagree on @mds1 that users would be confused on other icons, and think that this love to detail would give a more appreciated experience. its no usability issue but a loss for a high quality experience.
so i just could tweak some basics, but would love to revisit this topic when we have time for this …

wallet modal style update

---

app/src/store/wallet.ts
app/src/utils/alerts.ts
app/src/utils/chains.ts

Closes #275
To test, use connect with WalletConnect (WC) on Rinkeby and create a grant and/or checkout your cart. My current attempts at WC testing:
- Rainbow wallet's Rinkeby connection didn't seem to be working (the chainId is logged as 1)
- MetaMask connects to chainId but throws `TypeError: Failed to fetch` when I try to send a transaction. (I tried MetaMask + WC + Rinkeby on Uniswap and it throws with `Could not deposit invalid opcode: opcode 0xfe not defined`, so I don't think the problem is on our side)
Any recommendations on other WC wallets that support Rinkeby are welcome!

feat: add walletconnect support

---

dcurve/src/internal/calc/linear.ts
dcurve/src/internal/utils.ts
dcurve/src/types.ts

This PR will fix the linear calc to group and sum contributions by grantId and contributor.
--
Fixes: #302

bug: (dCurve) Groups and sums contributions for linear calc

---

app/package.json
app/src/components/GrantCard.vue
app/src/components/GrantDetailsRow.vue
app/src/components/GrantRoundCard.vue
app/src/components/GrantRoundDetailsRow.vue
app/src/store/wallet.ts
app/src/views/Cart.vue
app/tailwind.config.js
yarn.lock

as we discussed in 
https://github.com/dcgtc/dgrants/discussions/301
about image crop - i enabled the UI to work with ALL image dimensions by wrapping images into a container what is set to a specific aspect ratio, that masks the image nicely into the desired format . 
so we can bring images to any desired aspect ratio like this
```
<figure class="aspect-w-16 aspect-h-9">
</figure>
```
as the native css support for `aspect-ratio` is still not the best ( missing edge/IE ) i decided to go with a tailwind plugin 
https://github.com/tailwindlabs/tailwindcss-aspect-ratio
that works niceley - via the old "padding-bottom-trick" 
you need to rerun `yarn install` before you can see it working. 
if you want to try out how this truly looks with other dimension images you can easy replace the image …

image-aspect-ratio

---

app/src/utils/chains.ts

This PR moves us to the dcgtc deployed subgraph end-point.

chore: update matic subgraphUrl to use deployed graph

---

app/src/components/GrantCard.vue
app/src/store/data.ts
app/src/store/wallet.ts
app/src/utils/chains.ts
app/src/utils/data/grantRounds.ts

This PR fixes the `provider` `watch` by checking if the `contract` exists on the `provider` before populating the data store and ensures we clear all listeners on `startPolling`

fix: provider change watchers

---

app/package.json
app/src/components/GrantList.vue
app/src/shims.d.ts
app/src/views/Home.vue

resolves #381 
grant whitelist url is now set in .env instead of hard-coded
set `VITE_GRANT_WHITELIST_URI='https://storageapi.fleek.co/phutchins-team-bucket/dgrants/staging/whitelist-grants.json'` in .env file when testing
`
might need to update docs as well

create .env config for whitelist url

---

app/package.json
app/src/store/data.ts
app/src/utils/data/grantRounds.ts
app/src/utils/data/grants.ts
app/src/views/Home.vue
contracts/package.json
dcurve/package.json

This PR will move the metaPtr str replacement into the utility function which syncs the data with storage (this corrects the ptr currently stored in indexedDB without the need for cache busting).
--
Fixes: #467

fix: moves metaPtr update to getGrantRound

---

.gitignore
app/package.json
app/src/components/GrantList.vue
app/src/store/data.ts
app/src/views/GrantRegistryList.vue
app/src/views/GrantRoundGrants.vue
app/src/views/Home.vue
contracts/package.json
dcurve/package.json

- reduces calls to whitelist API
- ensure relevant grants are shown on the grants landing page
- moves the filter function to getAllGrants
Testing 
- ✅ Homepage shows filtered grants
- ✅Grants list shows filtered grants
- ✅ Next / Prev also shows filtered grants
- ✅ cart shows approved grants
- ✅ ~Access unapproved grants via URL  http://localhost:3000/#/dgrants/1?unverified=true~
closes https://github.com/dcgtc/dgrants/issues/451
closes https://github.com/dcgtc/dgrants/issues/407
closes https://github.com/dcgtc/dgrants/issues/429
~Q: Another way to go about this is to have a separate function in data.ts which just fetches the whitelist and have the frontend do the filtering
Q: As opposed to having data return grants. Would it make sense to return whitelistGrants and allGrants ?~
~What's …

chore: move whitelist to data.ts

---

app/package.json
app/src/components/GrantCard.vue
app/src/components/GrantList.vue
app/src/views/GrantRegistryGrantDetail.vue
app/src/views/GrantRound.vue
app/src/views/GrantRoundGrants.vue
contracts/package.json
dcurve/package.json
types/package.json
utils/package.json

fixed #464 
=====
For the last one, I think it's pretty nice already but @scco  should decide:

Breadcrumb now works as expected in #464

---

app/package.json
app/src/utils/chains.ts
contracts/package.json
dcurve/package.json
types/package.json
utils/package.json

This PR will reduce the `blockLimit` we have configured against polygon to match the `blockLimit` that the RPC endpoint is willing to accept.
--
Tested locally and this will allow staging to load.

fix: reduce configured blockLimit to match RPCs blockLimit

---

app/package.json
app/src/utils/constants.ts
app/src/utils/data/contributions.ts
app/src/utils/data/grantRounds.ts
app/src/utils/data/grants.ts
app/src/utils/utils.ts
contracts/package.json
dcurve/package.json
types/package.json
utils/package.json

This PR fixes the performance problems we have been experiencing...
- We we're making RPC calls for every block after the last event recorded by the graph to ensure that we had received all events up to the current block (incase the graph was behind for whatever reason) - however, because no new events had occurred for the last few days, we inadvertently reintroduced the issue which led us to move to the graph in the first place. Instead of attempting to close this gap, we will now only use RPC calls to fetch initial data as a fallback for if/when the graph fails (such as when there is no `SUBGRAPH_URL` for the chain). This requires additional testing - we still want to make sure the graph hasn't fallen behind, but we likely only need to introduce a constant buffer rather than starting …

Fixes performance issues

---

app/package.json
app/src/components/TransactionStatus.vue
app/src/store/cart.ts
app/src/store/data.ts
app/src/store/wallet.ts
app/src/utils/data/contributions.ts
app/src/utils/data/grantRounds.ts
app/src/utils/data/grants.ts
app/src/utils/utils.ts
app/src/views/GrantRegistryGrantDetail.vue

`DEFAULT_PROVIDER` from chains.ts  is now used for fetch operations instead of relying on the provider configured in the user's wallet.
Any contract interaction would continue use the rpc url configured in the wallet.
Refs: https://github.com/dcgtc/dgrants/issues/509

use default provider for fetch

---

app/package.json
app/src/utils/data/ipfs.ts
app/src/utils/utils.ts

Grants don't load due to face that metaPtr is not stored as MetaPtr but instead as a string on the metadata
This is causing the functions to error out.
The right way to do this would be to 
- fix create grant flow
- update grants metadata
The quick fix to unblock the team would be to get this PR in which does an error handling
Bug:

error handling: decode metadataId

---

app/package.json
app/src/utils/data/contributions.ts
app/src/utils/data/grants.ts
contracts/package.json
dcurve/package.json
types/package.json
types/src/grants.d.ts

This PR stores timestamps in to the models for `Grants` and `Contributions`
--
Tested locally

feat: records timestamps on grants and contributions

---

app/package.json
app/src/store/data.ts
app/src/utils/data/grants.ts
app/src/utils/utils.ts
app/src/views/Home.vue
contracts/package.json
dcurve/package.json
types/package.json
types/src/app.d.ts
utils/package.json

Whenever we fetch the whitelist I will cache it and in case of not being able to fetch the whitelist, I will use the cached one.
Also, put the fallback strategy into a new function so adding "Additionally we should add a fallback URL for the whitelist which could be a different IPFS gateway or HTTP server" must be pretty straightforward whenever the fallback URL is ready.
**Suggestion: Using the cache for whitelisting while trying to fetch whitelist, will give slightly better UX with faster load time**
fixed #459

Fixing whitelist

---

app/package.json
app/src/components/GrantCard.vue
app/src/components/GrantDetailsRow.vue
app/src/components/GrantRoundCard.vue
app/src/store/data.ts
app/src/utils/data/contributions.ts
app/src/utils/data/grantRounds.ts
app/src/utils/data/grants.ts
app/src/utils/data/ipfs.ts
app/src/utils/utils.ts
app/src/views/Cart.vue
app/src/views/GrantRoundsList.vue
app/src/views/Home.vue
contracts/package.json
dcurve/package.json
types/package.json
utils/package.json

This PR:
- ensures that we are lazy-loading metadata and shows placeholder content while we're waiting for the metaPtr content to be fetched from ipfs (Closes: #510)
- reduces the number of RPC calls we make on init
- allows for `metaPtr.protocol === 0` to default to placeholder images (Fixes: #532 && Fixes: #537)
- fixes typings on `cachedWhiteList` (`any` -> `LocalForageData`)
- only `checkIsDeployed` if were on dev (Fixes: #536)
--

fix: Lazy-load grant & grantRound metadata

---

app/package.json
app/src/utils/constants.ts
app/src/utils/data/ipfs.ts
app/src/utils/utils.ts
app/src/views/GrantRegistryGrantDetail.vue
app/src/views/GrantRegistryNewGrant.vue
contracts/package.json
dcurve/package.json
types/package.json
utils/package.json

fix logoURI split error 

---

app/package.json
app/src/store/settings.ts
app/src/store/wallet.ts
contracts/package.json
dcurve/package.json
types/package.json

Based on discussions here #299 it seems like the functionality we want is to keep the wallet disconnected when user clicks the disconnect wallet button, rather than auto reconnecting again on refresh. It will still auto reconnect on refresh when a user has their wallet connected.
closes #299

Disconnect wallet

---

app/package.json
app/vite.config.ts
contracts/package.json
dcurve/package.json
types/package.json

Resolves #555, see that issue for details
This is not yet tested since this issue only happens in production build. @phutchins do branches deploy to a staging env we can test this on before merging?

fix: 'require  is not defined' on prod for walletconnect

---

app/package.json
app/src/utils/data/ipfs.ts

This PR ensures that the `watch` method in data is triggered when the `GrantRounds` metadata is resolved.
--
Tested locally on Rinkeby

fix: ensure matching is calculated once metadata loads

---

app/package.json
dcurve/package.json
utils/package.json
utils/src/trustBonus.ts

This PR will fix the `414 Request-URI Too Large` error we are seeing in production
--
Tested the call locally

fix: moves to a post request when calling the trust-bonus endpoint

---

app/package.json
app/src/store/cart.ts

This PR will fix an error on the cart where we were checking the contents of the metadata before it was available/resolved.
--
Fixes: #577

fix: ensures metadata is present before checking the content of the grants property

---

app/.env.template
app/package.json
app/src/components/About.vue
app/src/shims.d.ts
contracts/package.json
dcurve/package.json
types/package.json

This PR adds the `VITE_DGRANTS_GRANT_ID` `.env` value to allow the `Donate to dGrants` button to be disabled/configured in the build.
--
Closes: #585

feat: allows for donate to dgrants btn to be disabled/configured

---

app/package.json
app/src/store/data.ts
app/src/utils/constants.ts
app/src/utils/data/grantRounds.ts
app/src/utils/data/grants.ts
app/src/utils/utils.ts
contracts/package.json
dcurve/package.json
types/package.json
types/src/grantRounds.d.ts

This PR adds a data utility to fetch `GrantRoundDonations` and exports `GrantRoundsDonations` from the data store.
--
Relates to: https://github.com/dcgtc/dgrants/issues/322#issuecomment-988965316
--
Depends on: https://github.com/dcgtc/dgrants-subgraph/pull/12
--
This can be tested on `Rinkeby` by updating the `subgraphUrl` to `https://api.thegraph.com/subgraphs/name/gdixon/dgrants-graph-rinkeby`

feat: adds `GrantRoundsDonations` to source all contributions by round

---

app/package.json
app/src/store/data.ts
contracts/package.json
dcurve/package.json
types/package.json

On page-load the `network.value` was `undefined` which caused the `immediate` watcher to clear the storage. 
This PR corrects that behaviour and will ensure that the cache persists between page reloads. 
--
Fixes: #587 
-- 
Tested locally

fix: ensures cache persists a page reload
