dcgtc/dgrants

.github/workflows/workflow.yml
contracts/package.json
package.json

Add workflow file

---

contracts/contracts/GrantRound.sol
contracts/contracts/GrantRoundFactory.sol
contracts/test/GrantRound.test.ts
contracts/test/GrantRoundFactory.test.ts

Add grant payout admin role to contract

---

README.md
contracts/.env.template
contracts/README.md
contracts/contracts/GrantRegistry.sol
contracts/contracts/GrantRound.sol
contracts/test/GrantRound.test.ts
contracts/test/utils.ts

- updates doc + .env template to make it clearer on what Infura to use
- updates doc to replace `yarn compile` with `yarn build` (as the former does not exist )
- fixes all lint issues that popup within the contract 
- fixes almost lint issues that show within the contract/tests (2 lint rules continue to fail )
**Before:** 
- [Linting Errors in Contract](https://user-images.githubusercontent.com/5358146/126417929-8148365a-8651-4c9d-a31e-9b207cb4d4e5.png)
- [Linting Errors in Contract Tests](https://user-images.githubusercontent.com/5358146/126418024-10d040b8-d0fb-43f2-8c34-03d531fbd9a2.png)
**After:** 
- [SEE HERE](https://user-images.githubusercontent.com/5358146/126422755-64e16ba3-ee2b-4d8b-b75b-d1610198a295.png)
We have errors in `timeTravel` and I wasn't able to figure out what …

chore: lint fixes + doc update

---

contracts/contracts/test/MockToken.sol
contracts/test/GrantRound.test.ts

Mock ERC20 tests for GrantRound 

---

contracts/test/GrantRound.test.ts

Time dependent fixtures

---

README.md

We are starting to see interest in contributing to this repo from the community, and allowing the community to help out would be a  nice dogfooding opportunity -- especially with a few jobs open (gitcoin.co/jobs).
Therefore this PR Adds a little Notice to the ReadMe about where the core devs are hanging out on discord... which hopefully will yield new young eager chat participants who want to join the team.

Adds Hiring Notice to the ReadMe

---

.github/workflows/workflow.yml
app/.lintstagedrc.js
app/package.json
app/src/components/BaseInput.vue
app/src/utils/utils.ts
app/src/views/GrantRegistryGrantDetail.vue
app/src/views/GrantRegistryList.vue
app/src/views/GrantRegistryNewGrant.vue
contracts/.eslintrc.yaml

Re: #27 , there is now a lint step in our workflow action

lint in workflow

---

.github/workflows/workflow.yml

add env secret to /test

---

contracts/contracts/GrantRound.sol
contracts/contracts/GrantRoundManager.sol
contracts/test/GrantRound.test.ts
contracts/test/GrantRoundManager.test.ts

Add matching pool token

---

README.md

Links in the `CONTRIBUTING.md` file on main readme.
This will be updated once https://github.com/dcgtc/dgrants/pull/92 is merged in

doc: link to contributing.md

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/task.md
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
CONTRIBUTING.md
README.md

- Adds a contributing.md guide to explain 
- the overall process we follow for discussions/issues/PR
- how to start contributing
- Adds Pull Request Template
- Adds Issue Template for
- bug
- task

chore: add CONTRIBUTING.md + create issue/PR templates

---

contracts/scripts/app.ts

- Add contribution fixtures when app is booted
- cleanup app.ts to improve readability by breaking each contract interaction into it's own function

chore: add contribution fixtures

---

app/package.json
app/src/components/BaseInput.vue
app/src/components/BaseSelect.vue
app/src/components/TransactionStatus.vue
app/src/index.css
app/src/main.ts
app/src/store/cart.ts
app/src/utils/alerts.ts
app/src/utils/utils.ts
app/src/views/Cart.vue
app/src/views/GrantRegistryGrantDetail.vue
app/src/views/GrantRegistryNewGrant.vue
app/src/views/GrantRoundDetails.vue
contracts/hardhat.config.ts
dcurve/package.json
utils/package.json
yarn.lock

Resolves #151, resolves #153
This PR is ready, but is dependent on #158 and was built off that branch. As a result, this is left as a draft with a target branch of `grant-details` to make the diff/commit history easier to review (otherwise it'd show the commits from the branch in #151. Once that PR is merged, I'll unmark this as draft and change the target branch
Changes:
- Adds notify.js as a dependency to show alerts
- Adds global error handler so all errors are surfaced to the user, with the exception of errors containing the strings in `messagesToIgnore`
- Updates cart checkout logic to first ensure user has sufficient allowance before prompting them to sign any transactions
- Updates cart UI to match figma mockups, with some placeholders for match amounts and USD conversions
- Add …

Cart UI conversion

---

app/src/components/BaseFilterNav.vue
app/src/components/BaseInput.vue
app/src/components/BaseTextarea.vue
app/src/components/GrantDetailsRow.vue
app/src/components/TransactionStatus.vue
app/src/index.css
app/src/utils/constants.ts
app/src/utils/utils.ts
app/src/views/Cart.vue
app/src/views/GrantRegistryGrantDetail.vue
app/src/views/GrantRegistryNewGrant.vue

- add component for TextArea
- implement form for creation + edit grants based on design

chore: refresh create + edit screen

---

app/src/App.vue

removing early css fragments not needed ( some parts badly affect the frontend )

clean app.vue from not needed css artifacts

---

CONTRIBUTING.md
app/README.md

docs: update readme and contributing files

---

.github/workflows/workflow.yml
README.md
app/.env.template
app/README.md
app/src/shims.d.ts
app/src/store/wallet.ts
app/src/utils/constants.ts
contracts/.env.template
contracts/hardhat.config.ts
contracts/package.json
contracts/test/__snapshots__/gas.test.ts.snap
contracts/test/expect.ts
contracts/test/gas.test.ts
contracts/test/snapshotGasCost.ts
yarn.lock

Closes #163 
Uses the same approach as Uniswap, described here: https://gist.github.com/gakonst/258a6ccd6bb752248999a13e8dd82a64
Below is a copy of the snapshot results that I manually augmented with USD prices assuming $3500 ETH and 100 gwei gas prices:
```
exports[`dGrants gas tests GrantRegistry createGrant 1`] = `166643` = ($58)
exports[`dGrants gas tests GrantRegistry updateGrantMetaPtr 1`] = `47021` = ($16)
exports[`dGrants gas tests GrantRegistry updateGrantMetaPtr 2`] = `54049` = ($18)
exports[`dGrants gas tests GrantRegistry updateGrantOwner 1`] = `41611` = ($14)
exports[`dGrants gas tests GrantRegistry updateGrantPayee 1`] = `41614` = ($14)
exports[`dGrants gas tests GrantRoundManager createGrantRound 1`] = `923202` = ($323)
exports[`dGrants gas tests GrantRoundManager five …
```

Gas snapshots

---

app/src/components/BaseInput.vue
app/src/components/BaseTextarea.vue
app/src/components/InputRow.vue
app/src/views/GrantRegistryNewGrant.vue

- Adding InputRow.vue
- Reworking BaseInput.vue / BaseTextarea.vue
- Apply these Components in /dgrants/new ( GrantRegistryNewGrant.vue )
This is a crucial PR what allow us to build forms as in design planed !
It will work nicely together with all the other components that are still waiting in my ui-branch ... 
An `<InputRow>` "wrapps" a v-slot for what ever input ( e.g. a `<BaseSelect>` or even vanilla `<input>` or what ever other `<div>stuff</div>` combination ) with its related label, description and a delete-icon (for later needed in other interfaces)
to achieve this, i had to remove the description and label from the `<BaseSelect>` & `<BaseTextarea>`
what shrinks down their html/css structure. i redesigned the error messages in these as well. i also removed that warning-icon part, as …

InputRow Component + Modify BaseInput / BaseTextarea + Rework CreateGrant UI

---

app/src/components/GrantDetailsRow.vue
app/src/components/GrantRoundDetailsRow.vue
app/src/store/cart.ts
app/src/utils/utils.ts
app/src/views/GrantRound.vue
contracts/scripts/ScriptLogger.ts
contracts/scripts/app.ts

Implements UI for GrantRound page
Needs rebase against https://github.com/dcgtc/dgrants/pull/188

chore: GrantRoundUI

---

app/src/store/data.ts
app/src/views/GrantRoundDetails.vue
contracts/contracts/GrantRegistry.sol
contracts/contracts/GrantRound.sol
contracts/contracts/GrantRoundManager.sol
contracts/hardhat.config.ts
contracts/scripts/app.ts
contracts/scripts/deploy-poc.config.ts
contracts/scripts/deploy-poc.ts
contracts/test/GrantRound.test.ts
contracts/test/GrantRoundManager.test.ts
contracts/test/__snapshots__/gas.test.ts.snap
contracts/test/gas.test.ts
types/src/grantRounds.d.ts

Contract cleanup

---

app/src/components/TransactionStatus.vue

closes #201
reworked this file as i noticed theres some issues in responsive views,
and also simplified the code a little bit, for better readability.

enhance ui for TransactionStatus.vue

---

app/src/store/cart.ts
app/src/views/GrantRegistryGrantDetail.vue
contracts/scripts/app.ts

Resolves #173 
- links should not show undefined
- link section should be removed if no links
- contribution section should be removed if no contributions

grant detail page tweaks

---

app/src/components/BaseHeader.vue
app/src/components/GrantRoundDetailsRow.vue
app/src/index.css
app/src/views/GrantRegistryGrantDetail.vue
app/src/views/GrantRound.vue

closes #209
- fixed the .intent in index.css  { was somehow not working for me ...  }
- fixing positioning of GrantRoundDetailsRow text elements / button
- removing the green from Add Funds
- add Tweet Button Design
- generating a rudimentary but probably not working tweet-link ( i created an issue #212 ) for this

Richard grants round design issue

---

app/src/components/ContributionRow.vue

enhance contributionrow ui

---

contracts/contracts/GrantRegistry.sol
contracts/contracts/GrantRound.sol
contracts/contracts/GrantRoundManager.sol
contracts/contracts/MerkleGrantRoundPayout.sol
contracts/test/GrantRegistry.test.ts
contracts/test/GrantRoundManager.test.ts
contracts/test/__snapshots__/gas.test.ts.snap
yarn.lock

Various contract improvements that don't impact functionality
**GrantRegistry**
- change memory parameters to calldata where possible
- tweak revert reason strings for consistency
- add validation to getter methods
**GrantRound**
- remove unused event
- tweak formatting for consistency
**MerkleGrantRoundPayout**
- fix typo in comments
- simplify assignment in _setClaimed
**GrantRoundManager**
- add SafeMath (lost it when downgrading from 0.8.x to 0.7.6)
- move GrantDonation before funds transfer to avoid potential for mismatched event ordering via reentrancy
- validate that output token of each swap is donationToken
- ensure donationRatios mapping always has storage fully cleared
- donation validation ensures the round and manager have the same registry
- remove unnecessary >= in …

Contract fixes

---

app/src/components/BaseHeader.vue
app/src/components/ContributionRow.vue
app/src/components/GrantCard.vue
app/src/components/GrantDetailsRow.vue
app/src/components/GrantRoundDetailsRow.vue
app/src/views/GrantRoundDetails.vue
types/CHANGELOG.md

- Replaces etherscan hardcoding with getEtherscanUrl
- lint fixes
closes #166

chore: use getEtherscanUrl

---

app/src/components/InputRow.vue
app/src/views/GrantRegistryGrantDetail.vue
app/src/views/GrantRegistryNewGrant.vue
app/src/views/GrantRound.vue

bug: fix broken edit page

---

app/src/router/index.ts
app/src/views/GrantRound.vue
app/src/views/GrantRoundDetails.vue
app/src/views/GrantRoundGrants.vue

Fix #150 
As discussed in [Discord](https://discord.com/channels/562828676480237578/838580829482647572/887326858562109440), I removed all the "contributing flow".
I left the "Create Grant" button as in GrantRegistryList. I can remove it if it's not necessary.

GrantRoundGrants

---

app/src/components/BaseImageUpload.vue
app/src/utils/data/ipfs.ts
app/src/utils/utils.ts
app/src/views/GrantRegistryGrantDetail.vue
app/src/views/GrantRegistryNewGrant.vue
contracts/scripts/app.ts

Grant Logo Metadata

---

app/src/components/GrantRoundCard.vue
app/src/views/GrantRoundsList.vue

This PR implements the GrantRound list page
---
---
Closes: #149

ui: Implements GrantRound list page

---

app/src/utils/utils.ts
app/src/views/GrantRegistryGrantDetail.vue
app/src/views/GrantRegistryNewGrant.vue

increase logo size limit to 512 kb as per our discord conversation

increase logo size limit to 512 kb

---

app/src/utils/data/utils.ts

not sure if anyone is still running into this issue, but I updated sync storage to only save if not already in storage

bug: duplicate grant fix

---

app/src/App.vue
app/src/components/LayoutHeader.vue
app/src/components/NetworkSelector.vue
app/src/store/wallet.ts
app/src/utils/chains.ts
app/src/utils/ethers.ts

Network selector updates

---

app/src/views/GrantRound.vue

This PR will fix loading a GrandRound after a refresh

Fixes GrantRound loading post refresh

---

app/src/utils/chains.ts

fix: remove trailing slash from explorer URL definitions

---

app/src/components/About.vue
app/src/components/BaseFilterNav.vue
app/src/components/Breadcrumb.vue
app/src/components/GrantCard.vue
app/src/components/GrantRoundCard.vue
app/src/components/LayoutHeader.vue
app/src/index.css
app/src/views/Cart.vue
app/src/views/Error404.vue
app/src/views/GrantRegistryGrantDetail.vue
app/src/views/GrantRound.vue

- Filter Nav : adding hover effect on nav elements
- Grant & Round Cards adding hover effect
- Cart : fixing structure to prevent double displayed "estimated matching" on multiple rounds
- Global Css : .link gets a hover effect and no underline but border-bottom line (looks nicer)
- about modal : apply .link to licens and help link
- Grant Card - apply .link to address
- Main Nav Menu ( When hover on logo ) : fixed broken css styles and semantic of the menu
- grantregistrygrantdetail & grantround : removed css from !loading
- design 404 page

design-fixes-5

---

app/src/utils/chains.ts
app/src/views/Cart.vue

- attempting to resolve #233 
- needs a site review as I'm not seeing the error
- small refactor for show / hide logic

equivalent amount zero

---

app/src/store/wallet.ts
app/src/views/Cart.vue
app/src/views/GrantRegistryGrantDetail.vue
app/src/views/GrantRegistryNewGrant.vue
app/src/views/GrantRound.vue

Fix #261 
Disable the button & don't' allow submissions on forms that trigger a tx.
- Create Grant
- Edit Grant
- Cart checkout
Am I missing any?

Disable form submissions that trigger a TX on wrong network

---

app/src/utils/utils.ts

Reduce dimension restriction for image upload

reduce image dimension to 500x500

---

app/src/router/index.ts
app/src/views/GrantRegistryNewGrant.vue
app/src/views/GrantSubmitted.vue

resolves #254, new styling for grant submitted page will come later from @scco

UI: grant submitted page

---

app/package.json
app/src/store/data.ts
app/src/utils/data/grants.ts
app/src/views/GrantRegistryGrantDetail.vue
contracts/package.json
contracts/scripts/app.ts
contracts/scripts/config/deploy-poc.config.ts
contracts/scripts/config/update-round.config.ts
contracts/test/__snapshots__/gas.test.ts.snap
contracts/test/gas.test.ts
dcurve/package.json

change ipfs endpoint for grants

---

app/package.json
app/src/utils/utils.ts
app/src/views/Home.vue
contracts/package.json
dcurve/package.json

Limits number of grants to be shown on homepage
closes https://github.com/dcgtc/dgrants/issues/450

limit to 8 grants on landing page

---

app/package.json
contracts/package.json
dcurve/package.json
doc/docs-web/README.md
doc/docs-web/docs/how-does-dgrants-work/concepts.md
doc/docs-web/docusaurus.config.js
doc/docs-web/src/css/custom.css
doc/docs-web/src/pages/index.js

Redoing the PR with all of the changes for PR #461

Jw fix docs redo

---

app/package.json
app/src/views/GrantRoundsList.vue
contracts/package.json
dcurve/package.json

This PR will ensure the completed grantRounds are listed correctly.
--
Closes: #471

fix: ensure completed grantRounds are listed correctly

---

app/package.json
app/src/views/Home.vue
contracts/package.json
dcurve/package.json

Show completed rounds on home page

---

app/package.json
contracts/contracts/GrantRound.sol
contracts/hardhat.config.ts
contracts/package.json
contracts/test/GrantRound.test.ts
contracts/test/__snapshots__/gas.test.ts.snap
dcurve/package.json

Closes #358 
As per our discussion after the POC is launched we will deploy this with the next release of contracts as well as the corresponding updates to the subgraph

Emit events for pool payouts and contributions

---

app/package.json
contracts/hardhat.config.ts
contracts/package.json
contracts/tasks/accounts.ts
contracts/tasks/execute-payouts.ts
contracts/tasks/payout-data/poc.data.ts
contracts/tasks/payouts-setup.ts
contracts/tasks/task-names.ts
dcurve/package.json

Closes #474, replaces #478
The new `execute-payouts.ts` task is the main file in this PR. The comments in that file as well as in `poc.data.ts` provide all relevant details on the scripts and how to use them

Match payouts script

---

app/package.json
contracts/contracts/GrantRegistry.sol
contracts/contracts/GrantRoundManager.sol
contracts/contracts/GrantRoundManagerUniV2.sol
contracts/package.json
contracts/test/GrantRegistry.test.ts
contracts/test/GrantRoundManager.test.ts
contracts/test/__snapshots__/gas.test.ts.snap
contracts/test/polygon/GrantRoundManagerUniV2.test.ts
contracts/test/utils.ts
dcurve/package.json
types/package.json
types/src/grants.d.ts
utils/package.json

Closes #488
- Adds `createdAt` and `lastUpdated` timestamps to grant registry (both in storage and events)
- Adds timestamps to donation logs

data fetching contract changes

---

app/package.json
contracts/contracts/GrantRegistry.sol
contracts/package.json
contracts/test/__snapshots__/gas.test.ts.snap
contracts/test/gas.test.ts
dcurve/package.json
types/package.json
utils/package.json

small PR - no need for storage modifier inside getGrantPayee function, also added gas cost test for getGrantPayee
branched off #497

getGrantPayee grant storage

---

app/package.json
contracts/package.json
dcurve/package.json
types/package.json
utils/package.json
utils/src/ipfs.ts

Updated the upload / update fleek API endpoint

update fleek URL

---

app/.env.template
app/package.json
app/src/App.vue
app/src/components/About.vue
app/src/shims.d.ts
app/src/views/ErrorMaintenance.vue
contracts/package.json
dcurve/package.json
doc/docs-web/docusaurus.config.js
types/package.json
utils/package.json

Closes #472 
- feat: add maintenance mode flag and page
- fix: twitter links now point to gitcoindao, not gitcoin

feat: add maintenance page

---

app/package.json
app/src/utils/data/ipfs.ts
contracts/package.json
contracts/scripts/config/deploy-gr12.config.ts
contracts/scripts/config/update-round.config.ts
dcurve/package.json
types/package.json
utils/package.json

update ipfs retrieval endpoints

---

app/package.json
app/src/views/GrantRound.vue

resolves #426 
side note: found more tech-debt, and will add it to the tech-debt issue

Show pending transaction when contributing to GrantRound

---

app/package.json
app/src/store/cart.ts
contracts/package.json
dcurve/package.json
types/package.json

fix: can now checkout even if grant is in an inactive round

---

app/package.json
app/src/store/data.ts
app/src/utils/data/grants.ts
contracts/package.json
dcurve/package.json
types/package.json

The root of the problem was grantListener. The grant listener was not handling getting metaPtr of new grants and updating the white list.

resolves #542

---

app/package.json
app/src/utils/data/ipfs.ts
contracts/package.json
dcurve/package.json
types/package.json

Allows you to create grant without logo
Closes https://github.com/dcgtc/dgrants/issues/551

fix: allow grant creation without logo

---

app/package.json
app/src/components/GrantCard.vue
app/src/components/GrantDetailsRow.vue
app/src/components/GrantOwnerCard.vue
app/src/components/GrantRoundCard.vue
app/src/components/GrantRoundDetailsRow.vue
app/src/components/LogoPtrImage.vue
app/src/utils/data/contributions.ts
app/src/utils/utils.ts
app/src/views/Cart.vue
app/src/views/MyGrants.vue
contracts/package.json
dcurve/package.json
types/package.json

This PR abstracts `ptrToURI()` calls to a component (`LogoPtrImage`) - this component should be responsible for the `logoPtr` handling and implementation details.
--
Fixes: #557

feat: adds component to contain `LogoPtr` image resolution and fallback process

---

app/package.json
app/src/components/GrantDetailsRow.vue

**While creating:** 
**After creating:**

bug: fix mismatch address

---

app/package.json
app/src/views/MyGrants.vue

Closes https://github.com/dcgtc/dgrants/issues/565

my-grants: show message if wallet is not connected

---

app/package.json
app/src/components/GrantCard.vue
app/src/components/GrantOwnerCard.vue
app/src/store/data.ts
app/src/views/GrantRegistryGrantDetail.vue

Ensure grantContributions always returns array and never undefined
closes https://github.com/dcgtc/dgrants/issues/569

chore: grantContributions should return []

---

app/package.json
app/src/utils/data/contributions.ts
contracts/package.json
dcurve/package.json
types/package.json
types/src/grants.d.ts

This PR ensures that the `grantDonationListener` is called and that the data is correctly stored in to localForage/indexedDB. 
--
Fixes: #552

fix: ensures `grantDonationListener` is called and successfully saves contribution data

---

app/package.json
app/src/views/GrantRegistryGrantDetail.vue
contracts/package.json
dcurve/package.json
types/package.json

resolves #580 and resolves #583
to test: try changing logo (using the edit form), and the previous logo is still showing up, see it fixed when testing this branch

fix logo updating

---

app/package.json
app/src/components/GrantCard.vue
app/src/components/GrantDetailsRow.vue
app/src/store/cart.ts
app/src/views/GrantRegistryGrantDetail.vue

fix: only allow donations if grant is whitelisted

---

app/package.json
app/src/components/LayoutHeader.vue

added card button in the nav when wallet is not connected

---

app/package.json
app/src/store/cart.ts
dcurve/package.json
dcurve/src/internal/utils.ts

- fixes the issue with regard to USDT
- ensures prediction diff is always used 
fixes https://github.com/dcgtc/dgrants/issues/594

fix: clr prediction estimates showing incorrect value

---

app/package.json
app/src/utils/data/contributions.ts
app/src/utils/utils.ts
app/src/views/GrantRound.vue
contracts/package.json
dcurve/package.json
types/package.json

closes #322 
(the view is updated)

Matching pool contributions

---

doc/protocol/protocol.md

Changes mostly focused around the format and headers that the protocol specification document should cover.

Protocol document updates
